### ISSUE TITLE
Detect social logins on the page

### ISSUE THREAD

**Issue by groovecoder** [mozilla/CookieRestrictionsShield#15]
See [list of social login provider scripts in the PHD](https://docs.google.com/document/d/1JeCS71Kf0ZJivxgNrrIvpViHCwU-QOhKvH92Av0b7Yc/edit#heading=h.n0bgif8ab7ce).

If any of these scripts are present, consider social logins present on the page.

**Comment by ericawright** [comment]
Only half-fixed as we still want to detect social logins from anchor tags and buttons which link to OAuth endpoints

**Comment by ehsan** [comment]
One way to do this is to see whether Gecko has stored a storage access permission for the URL of the top-level page.  The existence of such a permission is an indication that our heuristic that watches for these embedded widgets has been activated on the top level page.

Here is a sample code that shows how to detect this permission in JS:

```
  // assume URL is the URL of the page we want to test, eg. the top-level page
  let uri = Services.io.newURI(URL);
  for (let perm of Services.perms.getAllForURI(uri)) {
    if (!perm.type.startsWith("3rdPartyStorage^")) {
      continue;
    }
    // We have found our permission here!
    // The name of the third-party will appear after the ^ in the name of the permission.
    // The format of the name is:
    // "3rdPartyStorage^3RD_PARTY_ORIGIN{^OPENED_ORIGIN}"
    // where 3RD_PARTY_ORIGIN is the tracker domain and OPENED_ORIGIN is
    // an origin passed to window.open() by the tracker.  The part in braces is optional.
  }
```

**Comment by englehardt** [comment]
Here are sample sites that include each of the social login APIs, pulled from 2018-08-15 HTTPArchive data. Note that some of these sites may be NSFW.
* [Facebook](https://docs.google.com/spreadsheets/d/1-k3Rk2qnP0ZdzYGFft1Ee6cveXRlU6T5VwfsntO0TZ8/edit#gid=2124431238)
* [Google](https://docs.google.com/spreadsheets/d/1h5iiufe131MZUxLvpnrwKzuYr744u37ytAUZX0OyCgo/edit#gid=859108833)
* [Twitter](https://docs.google.com/spreadsheets/d/1RvHMkdtNZ8vuMmZx3tYWUjWV66Hb_RiHA4rpJ3h-cfE/edit#gid=1332956418)
* [LinkedIn](https://docs.google.com/spreadsheets/d/1l7EbYOJ0-vs-uloYZInZDmG46XXuby9usdB81qCzmno/edit#gid=1427543365)
* [Paypal](https://docs.google.com/spreadsheets/d/1Bhwg1kRe5oED4NWagdsBd7Pz73gLIKnah2ZELMv7-0M/edit#gid=1219283688)
* [Amazon](https://docs.google.com/spreadsheets/d/1_CzEKbewWeSCDiCMZNUZ25WIARVJDzZRItKFVKaztCE/edit#gid=951554783)
* Instagram: Since we've listed an oauth request URL for this, crawl data won't have the URL in the PHD. [These sites](https://docs.google.com/spreadsheets/d/199rc8NpkE896KsFhRU4X0Tu7UPE1G2Qndu-gzRfUXN4/edit#gid=734165083) make use of the instagram API (api.instagram.com)

**Comment by englehardt** [comment]
I did some spot checking on the sites above and have a few comments:
1. Many of those sites include the sdks but don't offer login (I checked between 5-10 sites for each list and found only a couple with social logins across all lists).
2. Many of the sites had some other type of social integration: a like button, tweets displayed on the page, a share button, etc. These are things that users may still interact with (and be prompted to login). This also isn't 100% however.
3. The Amazon login url appears to to longer be in use (at least not on the sites I checked). This is surprising given that the crawl data is less than a month old, but I suggest we drop that.

I think it's probably still worthwhile to collect the data given that it is an indication of problems with social integration, but not something that should be taken as an indication of problems with social login. For that, I think we'd need to detect the actual login flow as we discussed during the call today.

**Comment by ericawright** [comment]
we are sending a probe that detects if a password field is on the page, I suppose the two in conjunction could be read as a social login, otherwise just some sort of integration?

**Comment by englehardt** [comment]
That will catch pages that show "login with X" next to their normal login box. That's the most common pattern I've observed, but I've also seen some sites that have "Login with X" on the homepage or somewhere else that doesn't have a native login box (but none in the sites I sampled today).

**Comment by ericawright** [comment]
nice-to-have, but closing
